spring:
  application:
    name: Disaster Alerts

  datasource:
    url: jdbc:h2:file:./disasterdbtest

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true

  liquibase:
    change-log: db/changelog-test.yaml
    contexts: test

  h2:
    console:
      enabled: true
      path: /disasterdbtest

server:
  port: 8082