spring:
  application:
    name: Disaster Alerts

  docker:
    compose:
      file: compose-dev.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  liquibase:
    change-log: db/changelog-dev.yaml
    contexts: dev

server:
  port: 8080
