spring:
  main:
    banner-mode: log

  profiles:
    active: dev
    include: test

  mail:
    host: smtp.gmail.com
    port: 587
    username: disaster.alert1@gmail.com
    password: ihrbtliplvclxosl
#    username: disaster.alert2@gmail.com
#    password: mevizsenjlcrivvg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000