spring:
  main:
    banner-mode: log

  profiles:
    active: default

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: SA
    password:

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true

h2:
  console:
    enabled: true
    path: /h2-console